### PR TITLE
Vendor CLI11 library inside ignition-utils

### PR DESCRIPTION
**Pull request by mjcarroll**
Depends on: https://github.com/ignitionrobotics/ign-cmake/pull/143

Signed-off-by: Michael Carroll <michael@openrobotics.org>

### CODE REVIEW

**Review by caguero — COMMENTED** [review]
It looks good to me assuming that we're convinced that we want to vendor this library. My only suggestion would be to create a basic example to show how to use it in a very basic way.

**Comment by mjcarroll** [comment]
From @scpeters homebrew has a package: https://github.com/Homebrew/homebrew-core/blob/master/Formula/cli11.rb

**Comment by scpeters** [comment]
looks like it's in vcpkg as well: https://repology.org/project/cli11/versions

**Comment by mjcarroll** [comment]
@scepters and I discussed this with @j-rivero offline. Since this will only be used in executables, is header only, and has no existing Debian package, it makes sense to include the `CLI11` headers as part of the `ign-utils` install.

Additionally, rather than using the packaged versions for `vcpkg` and `homebrew` via cmake logic, we can use the same set of headers across all platforms for consistency.

This is still pending me developing a prototype for using this with `ign-tools`

**Comment by chapulina** [comment]
Closing and reopening to see if DCO takes effect

**Comment by azeey** [comment]
How do we deal with side-by-side installs in the future? We have used inline namespaces for this in our other packages, but CLI will have its own namespace. This could potentially be a problem down the road if we want to update the version of CLI we vendor.

**Comment by scpeters** [comment]
> How do we deal with side-by-side installs in the future? We have used inline namespaces for this in our other packages, but CLI will have its own namespace. This could potentially be a problem down the road if we want to update the version of CLI we vendor.

are you concerned about conflicting header file locations or conflicting symbols? I would expect CLI11 to only be used in executables, so I wouldn't expect problems with symbols

**Comment by azeey** [comment]
Yeah, I think you're right. If we limit its usage only to executables, we shouldn't have a problem.

**Review by scpeters — APPROVED** [review]
this seems to be working well enough with https://github.com/ignitionrobotics/ign-transport/pull/216

let's go ahead and merge and make a prerelease

**Comment by chapulina** [comment]
> let's go ahead and merge and make a prerelease

We could also use a nightly

**Comment by scpeters** [comment]
we don't have to wait a day if we make a prerelease now

**Pull request merged**
